"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.userRoutes = void 0;
const express_1 = require("express");
const userController_1 = require("../controllers/userController");
const favoriteController_1 = require("../controllers/favoriteController");
const authMiddleware_1 = require("../../src/middlewares/authMiddleware");
const router = (0, express_1.Router)();
router.get('/myProfile', authMiddleware_1.authenticateJWT, userController_1.userController.getProfile);
router.delete('/myProfile', authMiddleware_1.authenticateJWT, userController_1.userController.deleteUser);
router.post('/favorites/:courseId', authMiddleware_1.authenticateJWT, favoriteController_1.favoriteController.addFavoriteCourse);
router.delete('/favorites/:courseId', authMiddleware_1.authenticateJWT, favoriteController_1.favoriteController.removeFavoriteCourse);
router.get('/favorites', authMiddleware_1.authenticateJWT, favoriteController_1.favoriteController.getFavoriteCourses);
exports.userRoutes = router;
