services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - courses-service
      - auth-service
      - comment-service
      - enrollment-service
      - lesson-service

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    restart: always
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongo:27017/yourdb
    depends_on:
      - mongo

  courses-service:
    build:
      context: ./courses-service
      dockerfile: Dockerfile
    container_name: courses-service
    restart: always
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGO_URI=mongodb://mongo:27017/yourdb
    depends_on:
      - mongo

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    restart: always
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - MONGO_URI=mongodb://mongo:27017/yourdb
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo

  comment-service:
    build:
      context: ./comment-service
      dockerfile: Dockerfile
    container_name: comment-service
    restart: always
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - MONGO_URI=mongodb://mongo:27017/yourdb
    depends_on:
      - mongo

  enrollment-service:
    build:
      context: ./enrollment-service
      dockerfile: Dockerfile
    container_name: enrollment-service
    restart: always
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - MONGO_URI=mongodb://mongo:27017/yourdb
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - mongo
      - rabbitmq

  lesson-service:
    build:
      context: ./lesson-service
      dockerfile: Dockerfile
    container_name: lesson-service
    restart: always
    ports:
      - "3006:3006"
    environment:
      - PORT=3006
      - MONGO_URI=mongodb://mongo:27017/yourdb
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mongo-data:
