"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.lessonRoutes = void 0;
const express_1 = require("express");
const lessonController_1 = require("../controllers/lessonController");
const router = (0, express_1.Router)();
router.get('/', lessonController_1.lessonController.getAllLessons);
router.get('/:id', lessonController_1.lessonController.getLessonById);
router.post('/', lessonController_1.lessonController.createLesson);
router.put('/:id', lessonController_1.lessonController.updateLessonById);
router.delete('/:id', lessonController_1.lessonController.deleteLessonById);
exports.lessonRoutes = router;
