"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.commentRoutes = void 0;
const express_1 = require("express");
const commentController_1 = require("../controllers/commentController");
const router = (0, express_1.Router)();
router.get('/', commentController_1.commentController.getAllComments);
router.get('/:id', commentController_1.commentController.getCommentById);
router.post('/', commentController_1.commentController.createComment);
router.put('/:id', commentController_1.commentController.updateCommentById);
router.delete('/:id', commentController_1.commentController.deleteCommentById);
exports.commentRoutes = router;
